### ISSUE TITLE
How can we get album atwork?

### ISSUE THREAD

**Issue by Purwanto79** [hawkwynd/shoutcast-streamer#2]
How can we get album atwork and send to dashboard like on sample page? pleasee help..

**Comment by hawkwynd** [comment]
I will push an update to the repo, which handles the image capturing/display from discogs api.

**Comment by Purwanto79** [comment]
> I will push an update to the repo, which handles the image capturing/display from discogs api.

Hi hawkwynd.. thank you. I will wait for the update. I'm very interest for this project.

**Comment by hawkwynd** [comment]
> > I will push an update to the repo, which handles the image capturing/display from discogs api.
> 
> Hi hawkwynd.. thank you. I will wait for the update. I'm very interest for this project.



https://github.com/hawkwynd/tesseract

 -- I've finally gotten around to releasing my tesseract code which replaces this repo entirely. It uses discogs api. You'll need an api secret and key and add it to tessa2.js to work. Follow the README and let me know if you're having issues.

Thanks!
